"""create share notify table

Revision ID: 18202d01ebb0
Revises: 45ef91c289fb
Create Date: 2015-04-19 16:02:53.223668

"""

# revision identifiers, used by Alembic.
revision = '18202d01ebb0'
down_revision = '45ef91c289fb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share_notify',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('timeshared', sa.DateTime(), nullable=False),
    sa.Column('timeopened', sa.DateTime(), nullable=True),
    sa.Column('opened', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_share_notify_resource_id', 'share_notify', ['resource_id'], unique=False)
    op.create_index('ix_share_notify_user', 'share_notify', ['user'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_share_notify_user', table_name='share_notify')
    op.drop_index('ix_share_notify_resource_id', table_name='share_notify')
    op.drop_table('share_notify')
    ### end Alembic commands ###
