"""Getting rid of old User model

Revision ID: 1a96d24697da
Revises: 446663439e12
Create Date: 2015-04-13 12:25:05.701188

"""

# revision identifiers, used by Alembic.
revision = '1a96d24697da'
down_revision = '446663439e12'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('firstUse', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
