"""empty message

Revision ID: 222b4037be9c
Revises: None
Create Date: 2015-02-18 11:30:49.257678

"""

# revision identifiers, used by Alembic.
revision = '222b4037be9c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duplicate_scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_script', sa.String(), nullable=True),
    sa.Column('new_script', sa.String(), nullable=True),
    sa.Column('from_version', sa.Integer(), nullable=True),
    sa.Column('__key__', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('openIDData2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('federated_identity', sa.String(), nullable=True),
    sa.Column('federated_provider', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('migration_check',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('verified_to', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_migration_check_resource_id', 'migration_check', ['resource_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('firstUse', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('autosave', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_resource_versions_resource_id_version', 'resource_versions', ['resource_id', sa.text(u'version ASC')], unique=False)
    op.create_table('users_scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('permission', sa.String(), nullable=True),
    sa.Column('folder', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_scripts_resource_id_updated', 'users_scripts', ['resource_id', sa.text(u'last_updated DESC')], unique=False)
    op.create_table('script_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('autosave', sa.Boolean(), nullable=True),
    sa.Column('export', sa.String(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_script_data_resource_id_version', 'script_data', ['resource_id', sa.text(u'version ASC')], unique=False)
    op.create_index('ix_script_data_timestamp', 'script_data', ['timestamp'], unique=False)
    op.create_table('version_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_type', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('resource_version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resource_version_id'], ['resource_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('fk_version_tags_resource_version_id', 'version_tags', ['resource_version_id'], unique=False)
    op.create_table('ops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Integer(), nullable=True),
    sa.Column('offset', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('application_index', sa.Integer(), nullable=True),
    sa.Column('resource_version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resource_version_id'], ['resource_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('fk_ops_resource_version_id', 'ops', ['resource_version_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('fk_ops_resource_version_id', table_name='ops')
    op.drop_table('ops')
    op.drop_index('fk_version_tags_resource_version_id', table_name='version_tags')
    op.drop_table('version_tags')
    op.drop_index('ix_script_data_timestamp', table_name='script_data')
    op.drop_index('ix_script_data_resource_id_version', table_name='script_data')
    op.drop_table('script_data')
    op.drop_index('ix_users_scripts_resource_id_updated', table_name='users_scripts')
    op.drop_table('users_scripts')
    op.drop_index('ix_resource_versions_resource_id_version', table_name='resource_versions')
    op.drop_table('resource_versions')
    op.drop_table('users')
    op.drop_index('ix_migration_check_resource_id', table_name='migration_check')
    op.drop_table('migration_check')
    op.drop_table('openIDData2')
    op.drop_table('duplicate_scripts')
    ### end Alembic commands ###
