"""adding notes table

Revision ID: 23f00f06c871
Revises: cc389bc6eeb
Create Date: 2015-04-18 12:57:16.145142

"""

# revision identifiers, used by Alembic.
revision = '23f00f06c871'
down_revision = 'cc389bc6eeb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('row', sa.Integer(), nullable=True),
    sa.Column('col', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notes_resource_id', 'notes', ['resource_id'], unique=False)
    op.create_index('ix_notes_thread_id', 'notes', ['thread_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notes_thread_id', table_name='notes')
    op.drop_index('ix_notes_resource_id', table_name='notes')
    op.drop_table('notes')
    ### end Alembic commands ###
