"""Making folders relational in db

Revision ID: 26b47b50234a
Revises: 189ab50bb484
Create Date: 2015-08-07 11:32:25.229510

"""

# revision identifiers, used by Alembic.
revision = '26b47b50234a'
down_revision = '189ab50bb484'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folder_associations',
    sa.Column('screenplay_id', sa.Integer(), nullable=True),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ),
    sa.ForeignKeyConstraint(['screenplay_id'], ['screenplays.id'], )
    )
    with op.batch_alter_table('folders') as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_index('fk_folders_owner_id', ['owner_id'], unique=False)
        batch_op.create_foreign_key('fk_folders_users', 'users', ['owner_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folders') as batch_op:
        batch_op.drop_constraint('fk_folders_users', type_='foreignkey')
        batch_op.drop_index('fk_folders_owner_id', table_name='folders')
        batch_op.drop_column('owner_id')
        batch_op.drop_column('name')
    op.drop_table('folder_associations')
    ### end Alembic commands ###
