"""dropping unused fields in titlepage

Revision ID: 3b01ecc7b5c
Revises: 4f426bc4f0bc
Create Date: 2015-05-02 23:11:53.074648

"""

# revision identifiers, used by Alembic.
revision = '3b01ecc7b5c'
down_revision = '4f426bc4f0bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('title_page_data', 'authorThree')
    op.drop_column('title_page_data', 'migrated')
    op.drop_column('title_page_data', 'authorThreeChecked')
    op.drop_column('title_page_data', 'cell')
    op.drop_column('title_page_data', 'emailChecked')
    op.drop_column('title_page_data', 'registered')
    op.drop_column('title_page_data', 'phoneChecked')
    op.drop_column('title_page_data', 'cellChecked')
    op.drop_column('title_page_data', 'authorOne')
    op.drop_column('title_page_data', 'otherChecked')
    op.drop_column('title_page_data', 'authorTwo')
    op.drop_column('title_page_data', 'phone')
    op.drop_column('title_page_data', 'registeredChecked')
    op.drop_column('title_page_data', 'other')
    op.drop_column('title_page_data', 'based_onChecked')
    op.drop_column('title_page_data', 'address')
    op.drop_column('title_page_data', 'addressChecked')
    op.drop_column('title_page_data', 'authorTwoChecked')
    op.drop_column('title_page_data', 'email')
    op.drop_column('title_page_data', 'based_on')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('title_page_data', sa.Column('based_on', sa.VARCHAR(), nullable=True))
    op.add_column('title_page_data', sa.Column('email', sa.VARCHAR(), nullable=True))
    op.add_column('title_page_data', sa.Column('authorTwoChecked', sa.VARCHAR(), nullable=True))
    op.add_column('title_page_data', sa.Column('addressChecked', sa.VARCHAR(), nullable=True))
    op.add_column('title_page_data', sa.Column('address', sa.VARCHAR(), nullable=True))
    op.add_column('title_page_data', sa.Column('based_onChecked', sa.VARCHAR(), nullable=True))
    op.add_column('title_page_data', sa.Column('other', sa.VARCHAR(), nullable=True))
    op.add_column('title_page_data', sa.Column('registeredChecked', sa.VARCHAR(), nullable=True))
    op.add_column('title_page_data', sa.Column('phone', sa.VARCHAR(), nullable=True))
    op.add_column('title_page_data', sa.Column('authorTwo', sa.VARCHAR(), nullable=True))
    op.add_column('title_page_data', sa.Column('otherChecked', sa.VARCHAR(), nullable=True))
    op.add_column('title_page_data', sa.Column('authorOne', sa.VARCHAR(), nullable=True))
    op.add_column('title_page_data', sa.Column('cellChecked', sa.VARCHAR(), nullable=True))
    op.add_column('title_page_data', sa.Column('phoneChecked', sa.VARCHAR(), nullable=True))
    op.add_column('title_page_data', sa.Column('registered', sa.VARCHAR(), nullable=True))
    op.add_column('title_page_data', sa.Column('emailChecked', sa.VARCHAR(), nullable=True))
    op.add_column('title_page_data', sa.Column('cell', sa.VARCHAR(), nullable=True))
    op.add_column('title_page_data', sa.Column('authorThreeChecked', sa.VARCHAR(), nullable=True))
    op.add_column('title_page_data', sa.Column('migrated', sa.BOOLEAN(), nullable=True))
    op.add_column('title_page_data', sa.Column('authorThree', sa.VARCHAR(), nullable=True))
    ### end Alembic commands ###
