"""delete unused folder fields

Revision ID: 3c87bd302df2
Revises: 26b47b50234a
Create Date: 2015-09-04 18:21:38.551990

"""

# revision identifiers, used by Alembic.
revision = '3c87bd302df2'
down_revision = '26b47b50234a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('folders', 'data')
    op.drop_column('folders', 'user')
    op.drop_column('folders', '__key__')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folders', sa.Column('__key__', sa.VARCHAR(), nullable=True))
    op.add_column('folders', sa.Column('user', sa.VARCHAR(), nullable=True))
    op.add_column('folders', sa.Column('data', sa.VARCHAR(), nullable=True))
    ### end Alembic commands ###
