"""Added path field to blog

Revision ID: 446663439e12
Revises: 54afac78f149
Create Date: 2015-04-08 12:42:16.178567

"""

# revision identifiers, used by Alembic.
revision = '446663439e12'
down_revision = '54afac78f149'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('path', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'path')
    ### end Alembic commands ###
