"""new simplified colums for titlepage

Revision ID: 4cfa7120d410
Revises: 18202d01ebb0
Create Date: 2015-05-01 14:28:36.291500

"""

# revision identifiers, used by Alembic.
revision = '4cfa7120d410'
down_revision = '18202d01ebb0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('title_page_data', sa.Column('contact', sa.String(), nullable=False, server_default=''))
    op.add_column('title_page_data', sa.Column('migrated', sa.Boolean()))
    op.add_column('title_page_data', sa.Column('written_by', sa.String(), nullable=False, server_default=''))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('title_page_data', 'written_by')
    op.drop_column('title_page_data', 'migrated')
    op.drop_column('title_page_data', 'contact')
    ### end Alembic commands ###
