"""Table for raw data from appengine users

Revision ID: cc389bc6eeb
Revises: 24b7d0820015
Create Date: 2015-04-14 13:51:29.108316

"""

# revision identifiers, used by Alembic.
revision = 'cc389bc6eeb'
down_revision = '24b7d0820015'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appengine_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('firstUse', sa.DateTime(), nullable=True),
    sa.Column('verification_token', sa.String(), nullable=True),
    sa.Column('verified_email', sa.String(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('unsubscribe_token', sa.String(), nullable=True),
    sa.Column('unsubscribed', sa.Boolean(), nullable=True),
    sa.Column('reminder_sent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appengine_users')
    ### end Alembic commands ###
