"""Create Screenplay table, with relations only to users for now

Revision ID: f1292b5a6a5
Revises: 3b01ecc7b5c
Create Date: 2015-08-04 14:21:35.363652

"""

# revision identifiers, used by Alembic.
revision = 'f1292b5a6a5'
down_revision = '3b01ecc7b5c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screenplays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('is_trashed', sa.Boolean(), nullable=True),
    sa.Column('is_hard_deleted', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id')
    )
    op.create_index('fk_screenplays_owner_id', 'screenplays', ['owner_id'], unique=False)
    op.create_index('ix_screenplays_resource_id_updated', 'screenplays', ['resource_id', sa.text(u'last_updated DESC')], unique=False)
    op.create_table('collaborators',
    sa.Column('screenplay_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['screenplay_id'], ['screenplays.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collaborators')
    op.drop_index('ix_screenplays_resource_id_updated', table_name='screenplays')
    op.drop_index('fk_screenplays_owner_id', table_name='screenplays')
    op.drop_table('screenplays')
    ### end Alembic commands ###
