#!/bin/bash

E_BADARGS=65

if [ ! -n "$1" ]
then
  echo "usage: compile-js <page-to-compile>

for Example:
	./compile-js editor"
  exit $E_BADARGS
fi

args=("$@")
PAGE=${args[0]}

# make sure there's a good argument here

if [ "$PAGE" = "editor" ]
then
  echo "Compiling editor files..."
elif [ "$PAGE" = "titlepage" ]
then
  echo "Compiling titlepage files..."
else
  echo "
************ERROR: No such page $PAGE.*************
Choose from 'editor' or 'titlepage'.
***************************************************"
  exit $E_BADARGS
fi

#Get the root directory of the project
DIR="$( cd "$( dirname "$0" )" && pwd )"
cd $DIR
cd ..
ROOT=$(pwd)


# Remove old compiled file if exists
rm $ROOT"/static/js/min/"$PAGE"-compiled.js"

cd $ROOT"/static/js/restricted/"$PAGE 
cat *.js > $ROOT"/static/js/restricted/"$PAGE"-temp.js"

cd $ROOT"/static/closure-library/closure/bin"

I_FILE=$ROOT"/static/js/restricted/"$PAGE"-temp.js"
O_FILE=$ROOT"/static/js/min/"$PAGE"-temp-with-deps.js"
COMPILED_FILE=$ROOT"/static/js/min/"$PAGE"-compiled.js"
CL_ROOT=$ROOT"/static/closure-library/"
JQUERY=$ROOT"/scripts/jquery-externs.js"

python calcdeps.py -i $I_FILE -p $CL_ROOT -o script > $O_FILE
closure --compilation_level ADVANCED_OPTIMIZATIONS --externs $JQUERY --js $O_FILE > $COMPILED_FILE

rm $I_FILE $O_FILE
