#!/bin/bash


PAGE="editor"


#Get the root directory of the project
DIR="$( cd "$( dirname "$0" )" && pwd )"
cd $DIR
cd ..
ROOT=$(pwd)


# Remove old compiled file if exists
rm $ROOT"/static/js/min/"$PAGE"-compiled.js"

cd $ROOT"/static/js/restricted/"$PAGE 
cat *.js > $ROOT"/static/js/restricted/"$PAGE"-temp.js"

cd $ROOT"/static/closure-library/closure/bin"

I_FILE=$ROOT"/static/js/restricted/"$PAGE"-temp.js"
O_FILE=$ROOT"/static/js/min/"$PAGE"-temp-with-deps.js"
COMPILED_FILE=$ROOT"/static/js/min/"$PAGE"-compiled.js"
CL_ROOT=$ROOT"/static/closure-library/"
JQUERY=$ROOT"/scripts/jquery-externs.js"

python calcdeps.py -i $I_FILE -p $CL_ROOT -o script > $O_FILE
closure --compilation_level ADVANCED_OPTIMIZATIONS --externs $JQUERY --js $O_FILE > $COMPILED_FILE

rm $I_FILE $O_FILE
